version: '3.9'
services:
  # Wordpress auto configuration
  # depends on wp-cli build
  wp-auto-config:
    image: wpcli
    build: ./wpcli/
    container_name: ${COMPOSE_PROJECT_NAME}_wp_autoconfig
    entrypoint: sh -c "/wait && make -f /scripts/Makefile"
    volumes:
      - ${WORDPRESS_DATA_DIR}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - wordpress
    external_links:
      - ${WORDPRESS_DB_HOST}
    environment:
      # Waiting for mariadb and wordpress -------------------
      - WAIT_HOSTS=${WORDPRESS_DB_HOST}:3306
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
      # Wordpress configuration -----------------------------
      - WORDPRESS_LOCALE=${WORDPRESS_LOCALE:-en_US}
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mariadb}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_WEBSITE_TITLE=${WORDPRESS_WEBSITE_TITLE}
      - WORDPRESS_WEBSITE_URL=${WORDPRESS_WEBSITE_URL:-"http://localhost"}
      - WORDPRESS_WEBSITE_URL_WITHOUT_HTTP=${WORDPRESS_WEBSITE_URL:-localhost}
      - WORDPRESS_WEBSITE_POST_URL_STRUCTURE=${WORDPRESS_WEBSITE_POST_URL_STRUCTURE:-"/blog/%postname%/"}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_CUSTOM_HTTP_PORT=${WORDPRESS_CUSTOM_HTTP_PORT}
    networks:
      - database
      - wordpress

networks:
  database:
    external:
      name: wordpress_database_default
  wordpress:
    external:
      name: ${COMPOSE_PROJECT_NAME}_default